Repository minjune8506/2th-FISAgenda, pull requests merged in 2023-05, with the labels that each got.

#2 Feat/template
  .github/ISSUE_TEMPLATE/✅-feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#5 Feat/weather
  .gitignore
  images/구름많음-dark.png
  images/구름많음-white.png
  images/눈-dark.png
  images/눈-white.png
  images/번개-dark.png
  images/번개-white.png
  images/비-dark.png
  images/비-white.png
  images/화창-dark.svg
  images/화창-white.png
  package.json
  public/index.html
  server.js
Labels: enhancement

#6 전체적인 레이아웃 구성
  dist/output.css
  index.html
  index.js
  src/components/calendar.js
  src/images/logo.png
  src/styles/calendar.css
  src/styles/style.css
Labels: enhancement

#8 Feat/weather
  public/images/atmosphere-dark.png
  public/images/atmosphere-white.png
  public/images/clear-dark.svg
  public/images/clear-white.png
  public/images/clouds-dark.png
  public/images/clouds-white.png
  public/images/drizzle-dark.svg
  public/images/drizzle-white.svg
  public/images/rain-dark.png
  public/images/rain-white.png
  public/images/snow-dark.png
  public/images/snow-white.png
  public/images/thunderstorm-dark.png
  public/images/thunderstorm-white.png
  public/index.html
  public/weather.js
  server.js
Labels: enhancement

#10 Feat/calendar
  .gitignore
  dist/output.css
  index.html
  index.js
  package-lock.json
  package.json
  src/components/calendar.js
  src/date.js
  src/images/logo.png
  src/styles/calendar.css
  src/styles/style.css
  tailwind.config.js
Labels: enhancement

#12 Feat/change month
  dist/output.css
  index.html
  src/js/calendarButton.js
Labels: enhancement

#14 chore: lint, prettier 설정
  .eslintrc.json
  .prettierrc
  package.json
  public/weather.js
  src/components/calendar.js
  src/date.js
  src/js/calendarButton.js
Labels: enhancement

#19 Feat/label
  dist/output.css
  index.html
  src/components/calendar.js
  src/js/calendarButton.js
  src/js/calendarLabel.js
  src/styles/style.css
Labels: feature

#20 Feat/weather
  dist/output.css
  index.html
  index.js
  package-lock.json
  package.json
  public/index.html
  server.js
  src/images/atmosphere-dark.png
  src/images/atmosphere-white.png
  src/images/clear-dark.svg
  src/images/clear-white.png
  src/images/clouds-dark.png
  src/images/clouds-white.png
  src/images/drizzle-dark.svg
  src/images/drizzle-white.svg
  src/images/rain-dark.png
  src/images/rain-white.png
  src/images/snow-dark.png
  src/images/snow-white.png
  src/images/thunderstorm-dark.png
  src/images/thunderstorm-white.png
  src/js/app.js
  src/js/calendar.js
  src/js/calendarButton.js
  src/js/weather.js
  src/styles/style.css
Labels: feature

#27 feat: 라벨 여러개 불러오는 기능
  dist/output.css
  index.html
  src/js/calendar.js
  src/js/calendarButton.js
  src/styles/style.css
Labels: feature

#29 Bug/cors
  server.js
Labels: bug

#30 docs: README.md
  2th-fisagenda.gif
  README.md
Labels: docs

#32 feat: tooltip, meat 정보
  dist/output.css
  index.html
  src/images/favicon.ico
  src/js/calendar.js
  src/js/calendarLabel.js
  src/styles/style.css
Labels: feature

#33 README.md
  README.md
Labels: docs

#34 ver1.0
  .eslintrc.json
  .gitignore
  .prettierrc
  2th-fisagenda.gif
  README.md
  config.js
  dist/output.css
  index.html
  package-lock.json
  package.json
  server.js
  src/images/atmosphere-dark.png
  src/images/atmosphere-white.png
  src/images/clear-dark.svg
  src/images/clear-white.png
  src/images/clouds-dark.png
  src/images/clouds-white.png
  src/images/drizzle-dark.svg
  src/images/drizzle-white.svg
  src/images/favicon.ico
  src/images/logo.png
  src/images/nextButton.svg
  src/images/prevButton.svg
  src/images/rain-dark.png
  src/images/rain-white.png
  src/images/snow-dark.png
  src/images/snow-white.png
  src/images/thunderstorm-dark.png
  src/images/thunderstorm-white.png
  src/js/app.js
  src/js/calendar.js
  src/js/calendarButton.js
  src/js/calendarLabel.js
  src/js/weather.js
  src/styles/calendar.css
  src/styles/style.css
  tailwind.config.js
Labels: deploy
